# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2022-11-29 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text=b'A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(default=False, help_text=b'If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text=b'Once API key expires, clients cannot use it anymore.', null=True, verbose_name=b'Expires')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
            },
        ),
    ]